# Generated by Django 4.2.5 on 2023-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopchallange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='flow_file',
            field=models.CharField(default='', max_length=255),
        ),
    ]
